### PR TITLE
165 frontend headers, layouts and bugs

### PR DESCRIPTION
**Pull request by thienguen**
# What type of PR is this? (Check all that apply)

- [x] ✨**feature**: Introduces completely new code or new features.
- [x] 🐛**fix**: Implements changes that fix a bug. Ideally, reference an issue if present.
- [x] ♻️**refactor**: Includes any code-related change that is neither a fix nor a feature.
- [x] ✅**build**: Encompasses all changes related to the build of the software, including changes to dependencies or the addition of new ones.
- [x] ⚡️**test**: Pertains to all changes regarding tests, whether adding new tests or modifying existing ones.
- [x] 🚰**ci**: Involves all changes related to the configuration of continuous integration, such as GitHub Actions or other CI systems.
- [ ] 📚**docs**: Includes all changes to documentation, such as README files, or any other documentation present in the repository.
- [ ] 🗑️**chore**: Captures all changes to the repository that do not fit into the above categories.

# Description

What did you change? How did you change it?

1. remove shadcn entirely
2. `ci/cd` for API (currently on halt, since we yet to write test for the)
3. `dashboard structure, inbox structure, workout structure, and friends structure`
4. `TUI turbo` (experimental features, T side quest)
5. fixed `TRPC` typed, 
6. fixed `vitest` in API packages, and jest
7. have a `development build`
8. deploy on the web (through `expo`)
9. `prettier` config fixed to `single quote`
10. bug: bottom sheet for `gorhom`, so making my own Pick Modal
11. bug: `nativewind` is incomplete, that's why we have issue with tailwind not apply to some components. Current components that's known will break (`SafeViewArea`, `TouchOpacity`)
12. `Android` build now use `Java 17` instead of Java 11.
13. `expo SDK` is 50 (previously 49) 
14. added fonts (`Sora, IstokWeb`) -- through tailwind or style is fine
15. We are on latest of everything

---

# Tests

How was this tested?

- [x] Unit tests
- [ ] Integration tests
- [ ] E2E tests
- [x] Manual tests
- [ ] Tests were NOT needed
- [ ] Other (explain below)

---
## 1. build, and versions control

- [ ] since tons of versions had been done by me, to accommodate for bugs that keep breaking from legacy code, I would need you to `pnpm clean:workspaces` to clean the entire workspaces `node_module`
- [ ] `pnpm i` x3 (for safety)
- [ ] `bb1 && bb2` that good stuff
- [ ] ensure you can run this app through both `expo` and `development build` of ios (android it's fine)
- [ ] `tips`: delete the `.ios` folder so that it build fresh
- [ ] (optional) -- for `android` build, also delete `.android` folder and look at this [StackOverflow](https://stackoverflow.com/questions/27620262/sdk-location-not-found-define-location-with-sdk-dir-in-the-local-properties-fil) to setup your SDK
- [ ] i can't test on ios, so if someone can do that would be great

image

+ You will need to install new expo into virtual device

---
## 2. ui changed and structure proposed

- [ ] at first landed, you go on this

image

- [ ] the plus icon now have this instead (there is other animation (play around and see which you prefer) -- IN ADDITION, I have a cook animation for that, so i will cook it next pr. 

image

--> see video (can't attach here since it's too large)

image

+ Propose structure of our app, next issue I will organize others stuff. They start clutter up our spaces.

---
## 3. misc

- [ ] Open any files that has double quote, those in workout tracker folder is a good place to test
- [ ] format document (vscode it is shift + alt + r, or just execute your format on save setting

image

- [ ] how do we know it has run the formatted? --> check output (ctrl + shift + u)

image

- [ ] `cd packages/api` run `pnpm run vitest`

image

- [ ] in `api` folder, also try `pnpm run vitest-ui` 

image

- [ ] that is our backend testing for api (vitest is daway, I found jest to be slow af for me)
- [ ] imma need some man powers to write unit tests here, I'm doing designs and features.

### CODE REVIEW

**Comment by thienguen** [comment]
image

Due to the bottom sheet not fitting into the tab bar, I propose making it into the pop up. And also, bottom sheet we currently using is not the best, it bugged in our case

**Comment by thienguen** [comment]
Fall over from cycle 7

**Comment by mva919** [comment]
92 FILESSSS!!!????
image

**Review by mva919 — APPROVED** [review]
Tested on both android and ios and it works on development build, I just added a comment for a to do that we need to do. 🚀

**Comment by thienguen** [comment]
> Tested on both android and ios and it works on development build, I just added a comment for a to do that we need to do. 🚀

tysm ✨

**Comment by thienguen** [comment]
thank you for reviewing once again @mva919

**Pull request merged**
